[package]
name = "manifest-gen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.2.1"
clap = "2.27.0"
image = "0.23.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"