[package]
name = "manifest-gen"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "A manifest.json generator"
readme = "README.md"
repository = "https://github.com/fraol0912/manifest-gen"
homepage = "https://github.com/fraol0912/manifest-gen"

[dependencies]
inquire = "0.2.1"
clap = "2.27.0"
image = "0.23.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"